services:
  jekyll:
    build: .
    ports:
      - "4001:4001"
      - "35730:35730"
    volumes:
      - .:/site
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4001 --livereload --livereload-port 35730 --force_polling

volumes:
  bundle_cache:
